POST http://lb-72649560.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Jane Doe",
  "email": "janedoe1223233@example.com",
  "address": "456 main street",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2024-11-28"
}